@PetSearchAPI_HostAddress = http://localhost:5005

### Get Location Data for San Diego's zipcode.
GET {{PetSearchAPI_HostAddress}}/api/location/zipcode/92101
Accept: application/json

### Get Location Data for San Diego Zoo's coordinates.
GET {{PetSearchAPI_HostAddress}}/api/location/coordinates?latitude=32.7310927&longitude=-117.1543808
Accept: application/json

### Get a list of pets
GET {{PetSearchAPI_HostAddress}}/api/pets?type=dog&location=92101

### Get the second page of pet list with radius distance of 5 miles and sorted by oldest post
GET {{PetSearchAPI_HostAddress}}/api/pets?type=dog&location=92101&page=2&distance=5&sort=-recent

### Get the pet information with id: 71109141 
GET {{PetSearchAPI_HostAddress}}/api/pets/71109141

